# Generated by Django 4.2.1 on 2023-05-22 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('subject', models.CharField(max_length=200, null=True)),
                ('message', models.EmailField(max_length=500, null=True)),
            ],
        ),
    ]
